name: app
description: Cross-platform Mobile Application for VivaLaFocaccia

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta:
  equatable:
  provider:
  flutter_bloc:
  global_configuration:
  http:
  html:
  intl:

  flutter:
    sdk: flutter
  cached_network_image:
  transparent_image:
  cupertino_icons: ^0.1.3
  youtube_player_flutter: ^6.1.1
  bouncing_widget: ^1.2.0
  flutter_html:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cfg/
    - assets/
