name: app
description: Cross-platform Mobile Application for VivaLaFocaccia

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta:
  http:
  cached_network_image:
  html:
  intl:
  transparent_image:
  equatable:
  flutter_bloc:
  flutter_wordpress:
  global_configuration:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cfg/

